# Numpy Assignment

In [1]:
#Import NumPy as its abbreviation 'np'
import numpy as np

In [2]:
#Create a 1-dimensional NumPy array using np.array()
ar1 = np.array([1,2,3,4])
print("1-dimensional array : ")
print(ar1)

#Create a 2-dimensional NumPy array using np.array()
ar2 = np.array([[2,4,6,8,10],[1,3,5,7,9]])
print("2-dimensional array : ")
print(ar2)

1-dimensional array : 
[1 2 3 4]
2-dimensional array : 
[[ 2  4  6  8 10]
 [ 1  3  5  7  9]]


In [3]:
#Attributes of 1-dimensional array(shape, number of dimensions, data type, size and type)
ar1.shape,ar1.ndim,ar1.dtype,ar1.size,type(ar1)

((4,), 1, dtype('int64'), 4, numpy.ndarray)

In [4]:
#Attributes of 2-dimensional array
ar2.shape, ar2.ndim, ar2.dtype, ar2.size, type(ar2)

((2, 5), 2, dtype('int64'), 10, numpy.ndarray)

In [5]:
#Create an array of shape (5,5) with only ones
ar3 = np.ones([5,5])
ar3

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [6]:
#Create array of shape (3,3,5) with only zeros
ar4 = np.zeros((3,3,5))
ar4

array([[[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]])

In [7]:
#Create a random array with numbers between 0 and 10 of size(7,2)
np.random.randint(10, size=(7,2))

array([[2, 8],
       [5, 6],
       [8, 7],
       [3, 5],
       [1, 6],
       [4, 8],
       [6, 0]])

In [8]:
#Create a random array of floats between 0 and 1 of shape (3,5)
np.random.random((3,5))

array([[0.89971439, 0.76461754, 0.50212704, 0.96717501, 0.6863714 ],
       [0.34677769, 0.10942014, 0.226077  , 0.18645211, 0.53465866],
       [0.13959862, 0.43865335, 0.61300975, 0.61777284, 0.90456443]])

In [9]:
#Create an array of normally distributed random numbers
np.random.randn(int(input("number1 : ")),int(input("number2 : ")))

number1 : 2
number2 : 4


array([[-0.14248534, -0.72954388, -0.03418584, -0.16356994],
       [-1.374688  , -1.15060236, -0.87493085, -0.09645765]])

In [10]:
#set the random seed to 42
#Create a random array of numbers between 0 and 10 of size (4,6)
np.random.seed(42)
np.random.randint(10,size=(4,6))

array([[6, 3, 7, 4, 6, 9],
       [2, 6, 7, 4, 3, 7],
       [7, 2, 5, 4, 1, 7],
       [5, 1, 4, 0, 9, 5]])

In [11]:
#Copy the code from the cell above and run it again
np.random.seed(42)
rand = np.random.randint(10,size=(4,6))
rand


array([[6, 3, 7, 4, 6, 9],
       [2, 6, 7, 4, 3, 7],
       [7, 2, 5, 4, 1, 7],
       [5, 1, 4, 0, 9, 5]])

In [12]:
#Find the 0'th index of the 1 atleast array you created
rand[0]

array([6, 3, 7, 4, 6, 9])

In [13]:
#Get the first 2 rows of late st array you created
rand[:2]

array([[6, 3, 7, 4, 6, 9],
       [2, 6, 7, 4, 3, 7]])

In [14]:
#Get the first 2 values of the first 2 rows of the latest array
rand[:2,:2]

array([[6, 3],
       [2, 6]])

In [15]:
#Create a random array of numbers between 0 & 10 and an array of ones both of size (3,5),save them both to variables
ran = np.random.randint(10,size = (3,5))
ones = np.ones((3,5))
ran,ones

(array([[8, 0, 9, 2, 6],
        [3, 8, 2, 4, 2],
        [6, 4, 8, 6, 1]]),
 array([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]]))

In [16]:
#Add the two arrays together
ran+ones

array([[ 9.,  1., 10.,  3.,  7.],
       [ 4.,  9.,  3.,  5.,  3.],
       [ 7.,  5.,  9.,  7.,  2.]])

In [17]:
#Create another array of ones of shape(5,3)
ones1 = np.ones((5,3))
ones1


array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [18]:
#Try add the array of ones and the other most recent array together
#you can anticipate an error
ran+ones1

ValueError: operands could not be broadcast together with shapes (3,5) (5,3) 

In [19]:
#Do the same operation you just did but this time with a transpose on one array
tra = ran+ones1.T
tra

array([[ 9.,  1., 10.,  3.,  7.],
       [ 4.,  9.,  3.,  5.,  3.],
       [ 7.,  5.,  9.,  7.,  2.]])

In [20]:
#Take the latest array to the power of 2 using the python way
tra**2

array([[ 81.,   1., 100.,   9.,  49.],
       [ 16.,  81.,   9.,  25.,   9.],
       [ 49.,  25.,  81.,  49.,   4.]])

In [21]:
#Do the same thing with numpy way
np.power(tra,2)

array([[ 81.,   1., 100.,   9.,  49.],
       [ 16.,  81.,   9.,  25.,   9.],
       [ 49.,  25.,  81.,  49.,   4.]])

In [22]:
#Find the mean, min, max, standard deviation, variance of the latest array using np.mean()
np.mean(tra),np.min(tra),np.max(tra),np.std(tra),np.var(tra)

(5.6, 1.0, 10.0, 2.8000000000000003, 7.840000000000002)

In [23]:
#Create two arrays of random of random integers between 0 to 10 one of size(3,3) the other of size(3,2)
a1 = np.random.randint(10,size=(3,3))
a2 = np.random.randint(10,size=(3,2))
a1,a2

(array([[3, 8, 1],
        [9, 8, 9],
        [4, 1, 3]]),
 array([[6, 7],
        [2, 0],
        [3, 1]]))

In [24]:
#perform a dot product on the two newest arrays you created
np.dot(a1,a2)

array([[37, 22],
       [97, 72],
       [35, 31]])

In [25]:
#Create two arrays of random integers between 0 to 10 both of size (4,3)
b1 = np.random.randint(10,size=(4,3))
b2 = np.random.randint(10,size=(4,3))
b1,b2


(array([[7, 3, 1],
        [5, 5, 9],
        [3, 5, 1],
        [9, 1, 9]]),
 array([[3, 7, 6],
        [8, 7, 4],
        [1, 4, 7],
        [9, 8, 8]]))

In [26]:
#Perform a hadamard product on the two newest arrays you created
b1*b2

array([[21, 21,  6],
       [40, 35, 36],
       [ 3, 20,  7],
       [81,  8, 72]])

In [27]:
#Perform a dot product on the two newest arrays you ceated 
#Error anticipated
np.dot(b1,b2)

ValueError: shapes (4,3) and (4,3) not aligned: 3 (dim 1) != 4 (dim 0)

In [28]:

#Take the latest two arrays,perform a transpose on one of them and then perform a dot product on them both
np.dot(b1.T,b2)

array([[145, 168, 155],
       [ 63,  84,  81],
       [157, 146, 121]])

In [29]:
#Create two arrays of random integers between 0 and 10 of the same shape and save them to variables
c1 = np.random.randint(10,size=(2,3))
c2 = np.random.randint(10,size=(2,3))
c1,c2

(array([[0, 8, 6],
        [8, 7, 0]]),
 array([[7, 7, 2],
        [0, 7, 2]]))

In [30]:
#Compare the two arrays with '>','<='and '=='
c1>c2

array([[False,  True,  True],
       [ True, False, False]])

In [31]:
c1<=c2

array([[ True, False, False],
       [False,  True,  True]])

In [32]:
c1==c2

array([[False, False, False],
       [False,  True, False]])

In [33]:
#Sort one of the arrays you just created in ascending order
np.sort(c1)

array([[0, 6, 8],
       [0, 7, 8]])

In [34]:
#Sort the indexes of one of the arrays you just created
np.argsort(c1)

array([[0, 2, 1],
       [2, 1, 0]])

In [35]:
#Find the index with the maximum value in one of the arrays you've created
np.argmax(c1)


1

In [36]:
#Create an array with 10 evenly spaced numbers between 1 and 100
np.linspace(1,100,10)

array([  1.,  12.,  23.,  34.,  45.,  56.,  67.,  78.,  89., 100.])

In [37]:
#Find the indexes with the maximum values down the vertical axis of one of the arrays you created
np.argmax(c1,axis = 1)

array([1, 0])

In [38]:
#Find the indexes with the minimum values across the horizontal axis of one of the arrays you created
np.argmin(c1,axis = 0)

array([0, 1, 1])